import type { EasingFunctions } from '../lib/EasingFunctions';
import type { Input } from '../lib/Input';
import type { OMath } from '../lib/OMath';
import type { OS } from '../lib/OS';
import type { Time } from '../lib/Time';
import type { ScrollState } from './states/ScrollState';
declare class Scroll {
    current: number;
    current_state: ScrollState;
    default_cooldown: number;
    current_cooldown: number;
    delta: number;
    duration: number;
    easing_functions: EasingFunctions;
    enabled: boolean;
    framerate: number;
    input: Input;
    omath: OMath;
    os: OS;
    states: {
        [key: string]: ScrollState;
    };
    target: number;
    time: Time;
    constructor();
    init(input: Input, os: OS, omath: OMath, time: Time, easing_functions: EasingFunctions): void;
    get is_scrolling(): boolean;
    enable(): void;
    disable(): void;
    set_free_scrolling_by_steps(steps: number[], reset?: boolean): void;
    set_free_scrolling(from: number, to: number, reset?: boolean): void;
    set_step_scrolling(steps: number[], reset?: boolean): void;
    set_state(new_state: ScrollState): void;
    scroll_forward(): void;
    scroll_backward(): void;
    scroll_to(target: number): void;
    reset(target?: number): void;
    get_progress(): number;
    get_current_step(): number;
    get_current_step_index(): number;
    update(delta_x?: number, delta_y?: number): void;
}
declare const scroll: Scroll;
export { scroll as Scroll };
