export { scroll as Scroll };
declare const scroll: Scroll;
declare class Scroll {
    init(input: any, os: any, omath: any, time: any, easing_functions: any): void;
    input: any;
    os: any;
    omath: any;
    time: any;
    easing_functions: any;
    delta: any;
    current: number;
    target: number;
    duration: number;
    default_cooldown: number;
    current_state: any;
    enabled: boolean;
    states: {
        by_steps: ByStepsScrollState;
        by_steps_scrolling: ByStepsScrollingScrollState;
        free: FreeScrollState;
        free_by_steps: FreeByStepsScrollState;
    };
    get is_scrolling(): boolean;
    enable(): void;
    disable(): void;
    set_free_scrolling_by_steps(steps: any, reset?: boolean): void;
    set_free_scrolling(from: any, to: any, reset?: boolean): void;
    set_step_scrolling(steps: any, reset?: boolean): void;
    set_state(new_state: any): void;
    scroll_forward(): void;
    scroll_backward(): void;
    scroll_to(target: any): void;
    reset(target?: number): void;
    get_progress(): any;
    get_current_step(): any;
    get_current_step_index(): any;
    update(delta_x?: any, delta_y?: any): void;
}
import { ByStepsScrollState } from "./states/ByStepsScrollState";
import { ByStepsScrollingScrollState } from "./states/ByStepsScrollingScrollState";
import { FreeScrollState } from "./states/FreeScrollState";
import { FreeByStepsScrollState } from "./states/FreeByStepsScrollState";
