import type { AudioListener } from 'three';
import type { ResourceContainer } from '../lib/ResourceContainer';
import type { Time } from '../lib/Time';
import { AudioEvents } from './AudioEvents';
import { AudioMuffler } from './AudioMuffler';
declare class AudioManager {
    AudioListener: AudioListener;
    audio_events: AudioEvents;
    audio_mufflers: Record<string, AudioMuffler>;
    audio_mufflers_keys: string[];
    first_time_unmute: boolean;
    initialized: boolean;
    listener: AudioListener | undefined;
    loop_sounds: string[];
    max_volume: number;
    muted: boolean;
    muted_by_user: boolean;
    muting: boolean;
    paused_sounds: string[];
    resourse_container: ResourceContainer;
    sounds: Record<string, any>;
    sounds_names: Record<string, any>;
    sounds_to_play: string[];
    time: Time;
    init(audio_listener_klass: AudioListener, resourse_container: ResourceContainer, time: Time): void;
    init_sounds(scene_sounds_data: object[]): void;
    play(sound_names_array: string[] | string): void;
    pause(sound_name: string): void;
    unpause_sounds(): void;
    stop(sound_name: string): void;
    mute(muted_by_user?: boolean): void;
    unmute(): void;
    on_blur(): void;
    on_focus(): void;
    update(): void;
    stop_all_sounds(except_sound_names?: any[]): void;
    stop_all_loop_sounds(except_sound_names?: any[]): void;
    setup_sounds_names(sounds: object[]): void;
    get_sounds_names(sounds: object[]): string[];
}
declare const audio_manager: AudioManager;
export { audio_manager as AudioManager };
