export { audio_manager as AudioManager };
declare const audio_manager: AudioManager;
declare class AudioManager {
    init(audio_listener_klass: any, audio_context_klass: any, camera_manager: any, resourse_container: any, time: any, omath: any, os: any, easing_functions: any): void;
    AudioListener: any;
    AudioContext: any;
    camera_manager: any;
    resourse_container: any;
    time: any;
    omath: any;
    os: any;
    easing_functions: any;
    initialized: boolean;
    max_volume: number;
    sounds_names: {};
    sounds: {};
    loop_sounds: any[];
    audio_mufflers: {};
    audio_mufflers_keys: any[] | string[];
    sounds_to_play: any[];
    first_time_unmute: boolean;
    muted: boolean;
    muting: boolean;
    muting_t: any;
    muting_dir: number;
    listener: any;
    user_interaction: boolean;
    audio_unlocker: AudioUnlocker;
    bind_focus_events(): void;
    init_sounds(sound_names?: any[]): void;
    play(sound_names: any): void;
    stop(sound_name: any): void;
    mute(): void;
    unmute(): void;
    update(): void;
    stop_all_loop_sounds(except_sound_names?: any[]): void;
    setup_sounds_names(sounds: any): void;
    get_sounds_names(sounds: any): any[];
}
import { AudioUnlocker } from "./AudioUnlocker";
