export { audio_manager as AudioManager };
declare const audio_manager: AudioManager;
declare class AudioManager {
    init(audio_listener_klass: any, resourse_container: any, time: any): void;
    AudioListener: any;
    resourse_container: any;
    time: any;
    initialized: boolean;
    max_volume: number;
    sounds_names: {};
    sounds: {};
    loop_sounds: any[];
    audio_mufflers: {};
    audio_mufflers_keys: any[] | string[];
    sounds_to_play: any[];
    first_time_unmute: boolean;
    muted: boolean;
    muting: boolean;
    paused_sounds: any[];
    muted_by_user: boolean;
    listener: any;
    audio_events: AudioEvents;
    init_sounds(scene_sounds_data: any): void;
    play(sound_names_array: any): void;
    pause(sound_name: any): void;
    unpause_sounds(): void;
    stop(sound_name: any): void;
    mute(muted_by_user?: boolean): void;
    unmute(): void;
    on_blur(): void;
    on_focus(): void;
    update(): void;
    stop_all_sounds(except_sound_names?: any[]): void;
    stop_all_loop_sounds(except_sound_names?: any[]): void;
    setup_sounds_names(sounds: any): void;
    get_sounds_names(sounds: any): any[];
}
import { AudioEvents } from "./AudioEvents";
